/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChecklistIndexRouteImport } from './routes/_authenticated/checklist.index'
import { Route as AuthenticatedChecklistIdRouteImport } from './routes/_authenticated/checklist.$id'
import { Route as AuthenticatedChecklistNewRouteImport } from './routes/_authenticated/checklist.new'
import { Route as AuthenticatedConsultationsIndexRouteImport } from './routes/_authenticated/consultations.index'
import { Route as AuthenticatedConsultationsIdRouteImport } from './routes/_authenticated/consultations.$id'
import { Route as AuthenticatedConsultationsNewRouteImport } from './routes/_authenticated/consultations.new'
import { Route as AuthenticatedEddIndexRouteImport } from './routes/_authenticated/edd.index'
import { Route as AuthenticatedEddIdRouteImport } from './routes/_authenticated/edd.$id'
import { Route as AuthenticatedEddNewRouteImport } from './routes/_authenticated/edd.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChecklistIndexRoute =
  AuthenticatedChecklistIndexRouteImport.update({
    id: '/checklist/',
    path: '/checklist/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistIdRoute =
  AuthenticatedChecklistIdRouteImport.update({
    id: '/checklist/$id',
    path: '/checklist/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistNewRoute =
  AuthenticatedChecklistNewRouteImport.update({
    id: '/checklist/new',
    path: '/checklist/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsultationsIndexRoute =
  AuthenticatedConsultationsIndexRouteImport.update({
    id: '/consultations/',
    path: '/consultations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsultationsIdRoute =
  AuthenticatedConsultationsIdRouteImport.update({
    id: '/consultations/$id',
    path: '/consultations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsultationsNewRoute =
  AuthenticatedConsultationsNewRouteImport.update({
    id: '/consultations/new',
    path: '/consultations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEddIndexRoute = AuthenticatedEddIndexRouteImport.update({
  id: '/edd/',
  path: '/edd/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEddIdRoute = AuthenticatedEddIdRouteImport.update({
  id: '/edd/$id',
  path: '/edd/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEddNewRoute = AuthenticatedEddNewRouteImport.update({
  id: '/edd/new',
  path: '/edd/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/checklist/$id': typeof AuthenticatedChecklistIdRoute
  '/checklist/new': typeof AuthenticatedChecklistNewRoute
  '/consultations/$id': typeof AuthenticatedConsultationsIdRoute
  '/consultations/new': typeof AuthenticatedConsultationsNewRoute
  '/edd/$id': typeof AuthenticatedEddIdRoute
  '/edd/new': typeof AuthenticatedEddNewRoute
  '/checklist/': typeof AuthenticatedChecklistIndexRoute
  '/consultations/': typeof AuthenticatedConsultationsIndexRoute
  '/edd/': typeof AuthenticatedEddIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/checklist/$id': typeof AuthenticatedChecklistIdRoute
  '/checklist/new': typeof AuthenticatedChecklistNewRoute
  '/consultations/$id': typeof AuthenticatedConsultationsIdRoute
  '/consultations/new': typeof AuthenticatedConsultationsNewRoute
  '/edd/$id': typeof AuthenticatedEddIdRoute
  '/edd/new': typeof AuthenticatedEddNewRoute
  '/checklist': typeof AuthenticatedChecklistIndexRoute
  '/consultations': typeof AuthenticatedConsultationsIndexRoute
  '/edd': typeof AuthenticatedEddIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/checklist/$id': typeof AuthenticatedChecklistIdRoute
  '/_authenticated/checklist/new': typeof AuthenticatedChecklistNewRoute
  '/_authenticated/consultations/$id': typeof AuthenticatedConsultationsIdRoute
  '/_authenticated/consultations/new': typeof AuthenticatedConsultationsNewRoute
  '/_authenticated/edd/$id': typeof AuthenticatedEddIdRoute
  '/_authenticated/edd/new': typeof AuthenticatedEddNewRoute
  '/_authenticated/checklist/': typeof AuthenticatedChecklistIndexRoute
  '/_authenticated/consultations/': typeof AuthenticatedConsultationsIndexRoute
  '/_authenticated/edd/': typeof AuthenticatedEddIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/checklist/$id'
    | '/checklist/new'
    | '/consultations/$id'
    | '/consultations/new'
    | '/edd/$id'
    | '/edd/new'
    | '/checklist/'
    | '/consultations/'
    | '/edd/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/checklist/$id'
    | '/checklist/new'
    | '/consultations/$id'
    | '/consultations/new'
    | '/edd/$id'
    | '/edd/new'
    | '/checklist'
    | '/consultations'
    | '/edd'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/checklist/$id'
    | '/_authenticated/checklist/new'
    | '/_authenticated/consultations/$id'
    | '/_authenticated/consultations/new'
    | '/_authenticated/edd/$id'
    | '/_authenticated/edd/new'
    | '/_authenticated/checklist/'
    | '/_authenticated/consultations/'
    | '/_authenticated/edd/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist/': {
      id: '/_authenticated/checklist/'
      path: '/checklist'
      fullPath: '/checklist/'
      preLoaderRoute: typeof AuthenticatedChecklistIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist/$id': {
      id: '/_authenticated/checklist/$id'
      path: '/checklist/$id'
      fullPath: '/checklist/$id'
      preLoaderRoute: typeof AuthenticatedChecklistIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist/new': {
      id: '/_authenticated/checklist/new'
      path: '/checklist/new'
      fullPath: '/checklist/new'
      preLoaderRoute: typeof AuthenticatedChecklistNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultations/': {
      id: '/_authenticated/consultations/'
      path: '/consultations'
      fullPath: '/consultations/'
      preLoaderRoute: typeof AuthenticatedConsultationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultations/$id': {
      id: '/_authenticated/consultations/$id'
      path: '/consultations/$id'
      fullPath: '/consultations/$id'
      preLoaderRoute: typeof AuthenticatedConsultationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultations/new': {
      id: '/_authenticated/consultations/new'
      path: '/consultations/new'
      fullPath: '/consultations/new'
      preLoaderRoute: typeof AuthenticatedConsultationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edd/': {
      id: '/_authenticated/edd/'
      path: '/edd'
      fullPath: '/edd/'
      preLoaderRoute: typeof AuthenticatedEddIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edd/$id': {
      id: '/_authenticated/edd/$id'
      path: '/edd/$id'
      fullPath: '/edd/$id'
      preLoaderRoute: typeof AuthenticatedEddIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edd/new': {
      id: '/_authenticated/edd/new'
      path: '/edd/new'
      fullPath: '/edd/new'
      preLoaderRoute: typeof AuthenticatedEddNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedChecklistIdRoute: typeof AuthenticatedChecklistIdRoute
  AuthenticatedChecklistNewRoute: typeof AuthenticatedChecklistNewRoute
  AuthenticatedConsultationsIdRoute: typeof AuthenticatedConsultationsIdRoute
  AuthenticatedConsultationsNewRoute: typeof AuthenticatedConsultationsNewRoute
  AuthenticatedEddIdRoute: typeof AuthenticatedEddIdRoute
  AuthenticatedEddNewRoute: typeof AuthenticatedEddNewRoute
  AuthenticatedChecklistIndexRoute: typeof AuthenticatedChecklistIndexRoute
  AuthenticatedConsultationsIndexRoute: typeof AuthenticatedConsultationsIndexRoute
  AuthenticatedEddIndexRoute: typeof AuthenticatedEddIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedChecklistIdRoute: AuthenticatedChecklistIdRoute,
  AuthenticatedChecklistNewRoute: AuthenticatedChecklistNewRoute,
  AuthenticatedConsultationsIdRoute: AuthenticatedConsultationsIdRoute,
  AuthenticatedConsultationsNewRoute: AuthenticatedConsultationsNewRoute,
  AuthenticatedEddIdRoute: AuthenticatedEddIdRoute,
  AuthenticatedEddNewRoute: AuthenticatedEddNewRoute,
  AuthenticatedChecklistIndexRoute: AuthenticatedChecklistIndexRoute,
  AuthenticatedConsultationsIndexRoute: AuthenticatedConsultationsIndexRoute,
  AuthenticatedEddIndexRoute: AuthenticatedEddIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
